#dubbo conf
dubbo:
  application:
    name: ydsy-manager-web
  registry:
    address: zookeeper://127.0.0.1:2180
  consumer:
    timeout: 5000

#picture upload conf
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB

  redis:
    timeout: 10000
        # redis-single
    host: 127.0.0.1
    port: 6379
#tomcat conf
server:
  port: 8002

ydsy:
  salt: NXLH
  dev: true
  pageSize: 20
  oss-accesskeyid: LTAIR9AHFHts9Eov
  oss-accesskeyseret: q6n6e86CLhPrioNNnOssB2tGcheckms9G2m5q

  sms-accesskeyid: LTAIR9AHFHts9Eov
  sms-accesssecret: q6n6e86CLhPrioNNnOssB2tG9G2m5q
  userRedisExprie: 20


  wechat:
    appId: wxc417dc720f2f0759
    secret: 4ac1fbd9cce5ab525c14e80ab70c8592
    token: 111
    aesKey: 111
    msgDataFormat: JSON

    pay:
      appId: wxc417dc720f2f0759
      secret: 4ac1fbd9cce5ab525c14e80ab70c8592
      mchId: 1502936171
      mchKey: 25833201e2c5e6f5beae158d7da6fc90
      subAppId:
      subMchId:
      keyPath:
      notifyUrl: http://3s.dkys.org:21259/api/wx/order/paynotify








